In [1]:
#creating a tensor
import tensorflow as tf
tf.constant([[1.,2.,3.],[4.,5.,6.]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [2]:
#creating a tensor
t=tf.constant([[1.,2.,3.],[4.,5.,6.]])
t.shape

TensorShape([2, 3])

In [3]:
t.dtype

tf.float32

In [4]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [5]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [6]:
u=t+10
u

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [7]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [8]:
t@tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [9]:
from tensorflow import keras
K=keras.backend
K.square(K.transpose(t)+10)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[121., 196.],
       [144., 225.],
       [169., 256.]], dtype=float32)>

In [10]:
import numpy as np
a=np.array([2.,4.,5.])
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [11]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [16]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [17]:
tf.constant(2.)+tf.cast(4,tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [18]:
# customizing models and algos
#1.custom loss function
def huber_fn(y_true,y_pred):
    error=y_true-y_pred
    is_small=tf.abs(error)<1
    sq_loss=tf.square(error)/2
    linear_loss=tf.abs(error)-0.5
    return tf.where(is_small,sq_loss,linear_loss)

In [20]:
#creating a functional api to get the concept of callbacks
input_=keras.layers.Input(shape=X_train.shape[1:])
hid1=keras.layers.Dense(30,activation="relu")(input_)
hid2=keras.layers.Dense(30,activation="relu")(hid1)
concat=keras.layers.Concatenate()([input_,hid2])
output=keras.layers.Dense(1)(concat)
model=keras.Model(inputs=[input_],outputs=[output])

NameError: name 'X_train' is not defined

In [21]:
model.compile(loss=huber_fn,optimizer=nadam)

NameError: name 'model' is not defined